import java.awt.Desktop;
import java.awt.Desktop.Action;
import java.awt.FlowLayout;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * Created by MUSTAFA on 19.11.2016.
 */

public class NewJFrame extends javax.swing.JFrame implements Runnable{

    static BufferedReader input;
    static PrintWriter out;
    ArrayList<Result> ownResult = new ArrayList<Result>();
    public String result;
    private String []result1;

    public void sendRequest(String address) throws IOException{
        Socket s = new Socket(address, 9090);
        input  = new BufferedReader(new InputStreamReader(s.getInputStream()));
        out = new PrintWriter(s.getOutputStream());
    }


    public NewJFrame(String []site){
        result1=site;
    }

    public static void openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Action.BROWSE)) {
            try {
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public static void openWebpage(URL url) {
        try {
            openWebpage(url.toURI());
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    }


    /**
     * Creates new form NewJFrame
     */

    public static int pageIndex = 1;
    public static int maximumIndex = 0;

    public NewJFrame() {
        initComponents();
        hideElement();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soorch Online Searching Engine");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(900, 800));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setText("Did you mean ...?");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label1.setForeground(java.awt.Color.blue);
        label1.setText("label1");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label1MousePressed(evt);
            }
        });

        label2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label2.setForeground(java.awt.Color.blue);
        label2.setText("label2");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label2MousePressed(evt);
            }
        });

        label3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label3.setForeground(java.awt.Color.blue);
        label3.setText("label3");
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label3MousePressed(evt);
            }
        });

        label4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label4.setForeground(java.awt.Color.blue);
        label4.setText("label4");
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label4MousePressed(evt);
            }
        });

        label5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label5.setForeground(java.awt.Color.blue);
        label5.setText("label5");
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label5MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        jLabel6.setText("Page 1");

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("jLabel7");

        jMenu1.setText("History");

        jMenuItem2.setText("Github www.github.com 21.09.2016");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                                                                .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(label4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(345, 345, 345))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1)
                                                .addGap(54, 54, 54))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)))
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(125, 125, 125)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("ENTERA BASILDI");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        try {
            openWebpage(new URL("http://www.github.com"));
        } catch (MalformedURLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        AboutFrame aboutInstance = new AboutFrame();
        aboutInstance.setVisible(true);
    }//GEN-LAST:event_jMenu2MousePressed


    public void getData() {
        ownResult.clear();
        for( ;; ){

            try{
                String str = input.readLine();
                if(str.equals("-")) // done
                    return ;
                ownResult.add(new Result(str,input.readLine()));
            }catch(Exception e){
                System.err.println(e.getMessage());
            }
        }
    }

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        ArrayList<String> sites = new ArrayList<String>();
        ArrayList<String> siteDesc = new ArrayList<String>();

        if(jTextField1.getText().length() == 3){
            //JMenu1

            /*out.println(jTextField1.getText());
            out.flush();
            unhideElement();
            getData();*/

            ArrayList<Result> allResult = new ArrayList<Result>();
            for(int i = 0 ; i < ownResult.size(); i++)
                System.out.println(ownResult.get(i).getTitle() + "-" + ownResult.get(i).getUrl());
            for(int i = 0 ; i < ownResult.size(); i++)
                allResult.add(ownResult.get(i));

            if( ownResult.size() < 1){
                getDialog(this,"Sonuç Bulunamadı");
            }else if(ownResult.size() < 2){
                label2.setVisible(false);
                jLabel2.setVisible(false);
                label3.setVisible(false);
                jLabel3.setVisible(false);
                label4.setVisible(false);
                jLabel4.setVisible(false);
                label5.setVisible(false);
                jLabel5.setVisible(false);
            }else if(ownResult.size() < 3){
                label3.setVisible(false);
                jLabel3.setVisible(false);
                label4.setVisible(false);
                jLabel4.setVisible(false);
                label5.setVisible(false);
                jLabel5.setVisible(false);
            }else if(ownResult.size() < 4){
                label4.setVisible(false);
                jLabel4.setVisible(false);
                label5.setVisible(false);
                jLabel5.setVisible(false);
            }else if(ownResult.size() < 5){
                label5.setVisible(false);
                jLabel5.setVisible(false);
            }

            for(int i = 0 ; i <  ownResult.size(); i++)
            {
                label1.setText(ownResult.get(0).getTitle());
                jLabel1.setText(ownResult.get(0).getUrl());

                label2.setText(ownResult.get(1).getTitle());
                jLabel2.setText(ownResult.get(1).getUrl());

                label3.setText(ownResult.get(2).getTitle());
                jLabel3.setText(ownResult.get(2).getUrl());

                label4.setText(ownResult.get(3).getTitle());
                jLabel4.setText(ownResult.get(3).getUrl());

                label5.setText(ownResult.get(4).getTitle());
                jLabel5.setText(ownResult.get(4).getUrl());
            }


            JMenuItem addingItem = new JMenuItem(jTextField1.getText());
            jMenu1.add(addingItem);

        }else{
            getDialog(this,"Aramayı lütfen 3 harfli kelimeler ile yapın.");
        }
    }//GEN-LAST:event_jButton1MousePressed

    public void getDialog(JFrame aFrame, String message){
        JOptionPane.showMessageDialog(aFrame, message);
    }

    private void label1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MousePressed
        // TODO add your handling code here:
        /*
        System.out.println("TIKLANDI:d");

        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame("http://eksisozluk.com/");
                x.setVisible(true);

          }
    });
        */
    }//GEN-LAST:event_label1MousePressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Enter was pressed. Your code goes here.

        /*out.println(jTextField1.getText());
        out.flush();*/
            unhideElement();
            // getData();


            ArrayList<Result> allResult = new ArrayList<Result>();

            for(int i = 0 ; i < ownResult.size(); i++)
                System.out.println(ownResult.get(i).getTitle() + "-" + ownResult.get(i).getUrl());
            for(int i = 0 ; i < ownResult.size(); i++)
                allResult.add(ownResult.get(i));



            Result a = new Result("eksi","'http://eksisozluk.com'");
            ArrayList<Result> temp = new ArrayList<Result>();
            temp.add(a);
            temp.add(a);
            temp.add(a);
            temp.add(a);
            temp.add(a);
            temp.add(a);
            temp.add(a);
            temp.add(a);
            temp.add(a);
            temp.add(a);
            temp.add(a);
            temp.add(a);
            temp.add(a);
            ownResult = temp; // test amaclı ekledim

            for(int i = 0 ; i < 1 ; i++){
                String site = new String("'http://github.com'");
                String[] c = new String[] {"/bin/bash", "-c", "phantomjs /home/canerbakar/Desktop/github.js " + site};
                result1=c;
                (new Thread(new NewJFrame(result1))).start();

            }


            if(jTextField1.getText().length() == 3){
                //JMenu1
                unhideElement();

                if( ownResult.size() < 1){
                    getDialog(this,"Sonuç Bulunamadı");
                }else if(ownResult.size() < 2){
                    label2.setVisible(false);
                    jLabel2.setVisible(false);
                    label3.setVisible(false);
                    jLabel3.setVisible(false);
                    label4.setVisible(false);
                    jLabel4.setVisible(false);
                    label5.setVisible(false);
                    jLabel5.setVisible(false);
                }else if(ownResult.size() < 3){
                    label3.setVisible(false);
                    jLabel3.setVisible(false);
                    label4.setVisible(false);
                    jLabel4.setVisible(false);
                    label5.setVisible(false);
                    jLabel5.setVisible(false);
                }else if(ownResult.size() < 4){
                    label4.setVisible(false);
                    jLabel4.setVisible(false);
                    label5.setVisible(false);
                    jLabel5.setVisible(false);
                }else if(ownResult.size() < 5){
                    label5.setVisible(false);
                    jLabel5.setVisible(false);
                }


                for(int i = 0 ; i <  ownResult.size(); i++)
                {
                    label1.setText(ownResult.get(0).getTitle());
                    jLabel1.setText(ownResult.get(0).getUrl());

                    label2.setText(ownResult.get(1).getTitle());
                    jLabel2.setText(ownResult.get(1).getUrl());

                    label3.setText(ownResult.get(2).getTitle());
                    jLabel3.setText(ownResult.get(2).getUrl());

                    label4.setText(ownResult.get(3).getTitle());
                    jLabel4.setText(ownResult.get(3).getUrl());

                    label5.setText(ownResult.get(4).getTitle());
                    jLabel5.setText(ownResult.get(4).getUrl());
                }

                JMenuItem addingItem = new JMenuItem(jTextField1.getText());
                jMenu1.add(addingItem);


            }else{
                getDialog(this,"Aramayı lütfen 3 harfli kelimeler ile yapın.");
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void label2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MousePressed
        System.out.println("Label2 tıklandı");
        // TODO add your handling code here:
    }//GEN-LAST:event_label2MousePressed

    private void label3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MousePressed
        System.out.println("Label3 tıklandı");
        // TODO add your handling code here:
    }//GEN-LAST:event_label3MousePressed

    private void label4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MousePressed
        // TODO add your handling code here:,
        System.out.println("Label4 tıklandı");
    }//GEN-LAST:event_label4MousePressed

    private void label5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MousePressed
        // TODO add your handling code here:
        System.out.println("Label5 tıklandı");
    }//GEN-LAST:event_label5MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        System.out.println("Label1 DEsc tıklandı");
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        System.out.println("Label2 Desc tıklandı");
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        System.out.println("Label3 Desc tıklandı");
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        System.out.println("Label4 Desc tıklandı");
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        System.out.println("Label5 Desc tıklandı");
    }//GEN-LAST:event_jLabel5MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //resetElementHide();
        System.out.println("Page < tıklandı");
        System.out.println("OwnResult size = " + ownResult.size() );

        int maxIndex = ownResult.size() / 5;
        if(ownResult.size() % 5 != 0){
            maxIndex += 1;
        }
        System.out.println("MAX INDEX = " + maxIndex);

        if(pageIndex + 1 > maxIndex){
            getDialog(this," Maximum sayfa sayısı aşılamaz !");
        }else
        {
            pageIndex += 1;
            if(pageIndex == maxIndex){
                checkLastPage();
            }else{
                checkinterPages(pageIndex);
            }

            jLabel6.setText("Page "+pageIndex);
        }

        System.out.println("Şuan "+ pageIndex + ". sayfadasınız");
    }//GEN-LAST:event_jButton2ActionPerformed



    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int maxIndex = ownResult.size() / 5;
        if(ownResult.size() % 5 != 0){
            maxIndex += 1;
        }
        System.out.println("Page > tıklandı");
        System.out.println("OwnResult size = " + ownResult.size() );
        if(pageIndex - 1 < 1){
            getDialog(this," 0. sayfaya erişmeye çalıştınız");
        }else{
            pageIndex -= 1;
            if(pageIndex > 1){
                checkinterPages(pageIndex);
            }
            if(pageIndex == 1){
                checkFirstPage();
            }
            jLabel6.setText("Page "+pageIndex);
        }
        System.out.println("Şuan "+ pageIndex + ". sayfadasınız");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        try {
            displayImage();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formMouseClicked


    public void displayImage() throws IOException{

        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("/home/canerbakar/Desktop/http:/github.com.jpeg"));
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon icon=new ImageIcon(img);
        JFrame frame=new JFrame();
        frame.setLayout(new FlowLayout());
        frame.setSize(200,300);
        JLabel lbl=new JLabel();
        lbl.setIcon(icon);
        frame.add(lbl);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }


    public void checkinterPages(int pageInt){
        label1.setVisible(true);
        label1.setText(ownResult.get(pageInt*5).getUrl());
        label2.setVisible(true);
        label2.setText(ownResult.get(pageInt*5 + 1).getUrl());
        label3.setVisible(true);
        label3.setText(ownResult.get(pageInt*5 + 2).getUrl());
        label4.setVisible(true);
        label4.setText(ownResult.get(pageInt*5 + 3).getUrl());
        label5.setVisible(true);
        label5.setText(ownResult.get(pageInt*5 + 4).getUrl());
        jLabel1.setVisible(true);
        jLabel1.setText(ownResult.get(pageInt*5).getTitle());
        jLabel2.setVisible(true);
        jLabel2.setText(ownResult.get(pageInt*5 + 1).getTitle());
        jLabel3.setVisible(true);
        jLabel3.setText(ownResult.get(pageInt*5 + 2).getTitle());
        jLabel4.setVisible(true);
        jLabel4.setText(ownResult.get(pageInt*5 + 3).getTitle());
        jLabel5.setVisible(true);
        jLabel5.setText(ownResult.get(pageInt*5 + 4).getTitle());
    }

    public void checkFirstPage(){
        if(ownResult.size() >= 5){
            label1.setVisible(true);
            label1.setText(ownResult.get(0).getUrl());
            label2.setVisible(true);
            label2.setText(ownResult.get(1).getUrl());
            label3.setVisible(true);
            label3.setText(ownResult.get(2).getUrl());
            label4.setVisible(true);
            label4.setText(ownResult.get(3).getUrl());
            label5.setVisible(true);
            label5.setText(ownResult.get(4).getUrl());
            jLabel1.setVisible(true);
            jLabel1.setText(ownResult.get(0).getTitle());
            jLabel2.setVisible(true);
            jLabel2.setText(ownResult.get(1).getTitle());
            jLabel3.setVisible(true);
            jLabel3.setText(ownResult.get(2).getTitle());
            jLabel4.setVisible(true);
            jLabel4.setText(ownResult.get(3).getTitle());
            jLabel5.setVisible(true);
            jLabel5.setText(ownResult.get(4).getTitle());
        }else if(ownResult.size() % 5 == 1){
            label1.setText(ownResult.get(0).getUrl());
            label2.setVisible(false);
            label3.setVisible(false);
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel1.setText(ownResult.get(0).getTitle());
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
        }else if(ownResult.size() % 5 == 2){
            label1.setText(ownResult.get(0).getUrl());
            jLabel1.setText(ownResult.get(0).getTitle());
            label2.setText(ownResult.get(1).getUrl());
            jLabel2.setText(ownResult.get(1).getTitle());

            label3.setVisible(false);
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
        }else if(ownResult.size() % 5 == 3){
            label1.setText(ownResult.get(0).getUrl());
            jLabel1.setText(ownResult.get(0).getTitle());
            label2.setText(ownResult.get(1).getUrl());
            jLabel2.setText(ownResult.get(1).getTitle());
            label3.setText(ownResult.get(2).getUrl());
            jLabel3.setText(ownResult.get(2).getTitle());
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
        }else if(ownResult.size() % 5 == 4){
            label1.setText(ownResult.get(0).getUrl());
            jLabel1.setText(ownResult.get(0).getTitle());
            label2.setText(ownResult.get(1).getUrl());
            jLabel2.setText(ownResult.get(1).getTitle());
            label3.setText(ownResult.get(2).getUrl());
            jLabel3.setText(ownResult.get(2).getTitle());
            label4.setText(ownResult.get(3).getUrl());
            jLabel4.setText(ownResult.get(3).getTitle());
            label4.setVisible(false);
            jLabel4.setVisible(false);
        }else
        {
            System.out.println("Else case");
        }
    }

    public void checkLastPage(){
        if(ownResult.size() % 5 == 0){
            label1.setVisible(true);
            label2.setVisible(true);
            label3.setVisible(true);
            label4.setVisible(true);
            label5.setVisible(true);
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel7.setVisible(true);

            label1.setText(ownResult.get(ownResult.size()-5).getUrl());
            jLabel1.setText(ownResult.get(ownResult.size()-5).getTitle());
            label2.setText(ownResult.get(ownResult.size()-4).getUrl());
            jLabel2.setText(ownResult.get(ownResult.size()-4).getTitle());
            label3.setText(ownResult.get(ownResult.size()-3).getUrl());
            jLabel3.setText(ownResult.get(ownResult.size()-3).getTitle());
            label4.setText(ownResult.get(ownResult.size()-2).getUrl());
            jLabel4.setText(ownResult.get(ownResult.size()-2).getTitle());
            label5.setText(ownResult.get(ownResult.size()-1).getUrl());
            jLabel5.setText(ownResult.get(ownResult.size()-1).getTitle());


        }else if(ownResult.size() % 5 == 1){
            label2.setVisible(false);
            label3.setVisible(false);
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);

            label1.setText(ownResult.get(ownResult.size()-5).getUrl());
            jLabel1.setText(ownResult.get(ownResult.size()-5).getTitle());
            label2.setText(ownResult.get(ownResult.size()-4).getUrl());
            jLabel2.setText(ownResult.get(ownResult.size()-4).getTitle());
            label3.setText(ownResult.get(ownResult.size()-3).getUrl());
            jLabel3.setText(ownResult.get(ownResult.size()-3).getTitle());
            label4.setText(ownResult.get(ownResult.size()-2).getUrl());
            jLabel4.setText(ownResult.get(ownResult.size()-2).getTitle());
            label5.setText(ownResult.get(ownResult.size()-1).getUrl());
            jLabel5.setText(ownResult.get(ownResult.size()-1).getTitle());

        }else if(ownResult.size() % 5 == 2){
            label3.setVisible(false);
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);

            label1.setText(ownResult.get(ownResult.size()-5).getUrl());
            jLabel1.setText(ownResult.get(ownResult.size()-5).getTitle());
            label2.setText(ownResult.get(ownResult.size()-4).getUrl());
            jLabel2.setText(ownResult.get(ownResult.size()-4).getTitle());
            label3.setText(ownResult.get(ownResult.size()-3).getUrl());
            jLabel3.setText(ownResult.get(ownResult.size()-3).getTitle());
            label4.setText(ownResult.get(ownResult.size()-2).getUrl());
            jLabel4.setText(ownResult.get(ownResult.size()-2).getTitle());
            label5.setText(ownResult.get(ownResult.size()-1).getUrl());
            jLabel5.setText(ownResult.get(ownResult.size()-1).getTitle());
        }else if(ownResult.size() % 5 == 3){
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            label1.setText(ownResult.get(ownResult.size()-5).getUrl());
            jLabel1.setText(ownResult.get(ownResult.size()-5).getTitle());
            label2.setText(ownResult.get(ownResult.size()-4).getUrl());
            jLabel2.setText(ownResult.get(ownResult.size()-4).getTitle());
            label3.setText(ownResult.get(ownResult.size()-3).getUrl());
            jLabel3.setText(ownResult.get(ownResult.size()-3).getTitle());
            label4.setText(ownResult.get(ownResult.size()-2).getUrl());
            jLabel4.setText(ownResult.get(ownResult.size()-2).getTitle());
            label5.setText(ownResult.get(ownResult.size()-1).getUrl());
            jLabel5.setText(ownResult.get(ownResult.size()-1).getTitle());

        }else if(ownResult.size() % 5 == 4){
            label4.setVisible(false);
            jLabel4.setVisible(false);

            label1.setText(ownResult.get(ownResult.size()-5).getUrl());
            jLabel1.setText(ownResult.get(ownResult.size()-5).getTitle());
            label2.setText(ownResult.get(ownResult.size()-4).getUrl());
            jLabel2.setText(ownResult.get(ownResult.size()-4).getTitle());
            label3.setText(ownResult.get(ownResult.size()-3).getUrl());
            jLabel3.setText(ownResult.get(ownResult.size()-3).getTitle());
            label4.setText(ownResult.get(ownResult.size()-2).getUrl());
            jLabel4.setText(ownResult.get(ownResult.size()-2).getTitle());
            label5.setText(ownResult.get(ownResult.size()-1).getUrl());
            jLabel5.setText(ownResult.get(ownResult.size()-1).getTitle());
        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */



        /*try {
            //sendRequest("10.1.96.131");
            Socket s = new Socket("10.1.96.131", 9090);
            input  = new BufferedReader(new InputStreamReader(s.getInputStream()));
            out = new PrintWriter(s.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }*/

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    /* Elementleri saklar */
    public void hideElement(){
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        label1.setVisible(false);
        label2.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        jButton3.setVisible(false);
        jButton2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
    }

    /* Elementleri gösterir */
    public void unhideElement(){
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        label1.setVisible(true);
        label2.setVisible(true);
        label3.setVisible(true);
        label4.setVisible(true);
        label5.setVisible(true);
        jButton3.setVisible(true);
        jButton2.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Process proc = null;

        try{
            System.out.println(getSite());
            proc = new ProcessBuilder(getSite()).start();
        }catch (IOException e) {
            e.printStackTrace();
        }

        try{
            proc.waitFor();
        }catch (InterruptedException e) {
            e.printStackTrace();
        }

    }

    public void setSite(String []site){
        result1=site;
    }

    public String []getSite(){
        return result1;
    }

}


