
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
//import java.util.;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.xml.bind.DatatypeConverter;
import org.apache.commons.codec.binary.Base64;


/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static Object lock = new Object();
    static BufferedReader input;
    static PrintWriter out;
    ArrayList<Result> ownResult = new ArrayList<Result>();
    public String result;
    private String []result1;
    FileWriter fw;
    
    public static void sendRequest(String address) throws IOException{
        Socket s = new Socket(address, 8080);
        input  = new BufferedReader(new InputStreamReader(s.getInputStream()));
        out = new PrintWriter(s.getOutputStream());               
    }
    
    
    public NewJFrame(String []site){
        result1=site;
    }
    
    public static void openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public static void openWebpage(URL url) {
        try {
            openWebpage(url.toURI());
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    }
    
  
    /**
     * Creates new form NewJFrame
     */
    
    public static int pageIndex = 1;
    public static int maximumIndex = 0;
    
    public NewJFrame() throws FileNotFoundException, IOException {
        initComponents();
        hideElement();
        String str;
        FileReader fr;
        File fileDir = new File("/home/canerbakar/Desktop/historyLog.txt");
        
        BufferedReader bw = new BufferedReader(
                    new InputStreamReader(
                            new FileInputStream(fileDir)));
        
        while ((str = bw.readLine()) != null) {
            JMenuItem addingItem = new JMenuItem(toDecode(str));
            jMenu1.add(addingItem);
        }
        
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soorch Online Searching Engine");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(900, 800));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setText("Did you mean ...?");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label1.setForeground(java.awt.Color.blue);
        label1.setText("label1");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label1MousePressed(evt);
            }
        });

        label2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label2.setForeground(java.awt.Color.blue);
        label2.setText("label2");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label2MousePressed(evt);
            }
        });

        label3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label3.setForeground(java.awt.Color.blue);
        label3.setText("label3");
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label3MousePressed(evt);
            }
        });

        label4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label4.setForeground(java.awt.Color.blue);
        label4.setText("label4");
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label4MousePressed(evt);
            }
        });

        label5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label5.setForeground(java.awt.Color.blue);
        label5.setText("label5");
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label5MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        jLabel6.setText("Page 1");

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });

        jMenu1.setText("History");

        jMenuItem2.setText("Github www.github.com 21.09.2016");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jLabel11.getAccessibleContext().setAccessibleName("JLabel11");

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("ENTERA BASILDI");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        try {
            openWebpage(new URL("http://www.github.com"));
        } catch (MalformedURLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        AboutFrame aboutInstance = new AboutFrame();
        aboutInstance.setVisible(true);
    }//GEN-LAST:event_jMenu2MousePressed

    
    public void getData1() throws IOException {
        ownResult.clear();
        String str=new String();
      

        str =   input.readLine();
        int numData1 = Integer.parseInt(str);

        
        for( int i=0; i<numData1; ++i ){
            
            try{
                String str1 = input.readLine();  
                ownResult.add(new Result(str1,input.readLine()));
            }catch(Exception e){
                System.err.println(e.getMessage());
            }
        
        
        }
        
        for(int i=0; i<numData1; ++i){

            StringBuilder path = new StringBuilder();
            path.append("/home/canerbakar/Desktop/filesendtestfolder1/");
            path.append(i);
            path.append(".jpg");

            str = input.readLine();
            byte[] decodedBytes =  Base64.decodeBase64(str);

            //create file
            File file = new File(path.toString());
            file.createNewFile();

            OutputStream outFile = new FileOutputStream(file);
            outFile.write(decodedBytes);
            outFile.close();
        }
        
    }
    
    
    public void getData(String search) throws IOException {
        ownResult.clear();
        String str=new String();
      

        str =   input.readLine();
        int numData = Integer.parseInt(str);
        String str2 =   input.readLine();
        int numData1 = Integer.parseInt(str2);
        
        for( int i=0; i<numData1; ++i ){
            
            try{
                String str1 = input.readLine();  
                ownResult.add(new Result(str1,input.readLine()));
            }catch(Exception e){
                System.err.println(e.getMessage());
            }
        
        
        }
        
        for(int i=0; i<numData1; ++i){

            StringBuilder path = new StringBuilder();
            path.append("/home/canerbakar/Desktop/filesendtestfolder1/");
            path.append(i);
            path.append(".jpg");

            str = input.readLine();
            byte[] decodedBytes =  Base64.decodeBase64(str);

            //create file
            File file = new File(path.toString());
            file.createNewFile();

            OutputStream outFile = new FileOutputStream(file);
            outFile.write(decodedBytes);
            outFile.close();
        }
        
    }
     
     
    
    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // Search button clicked.
        
        out.println(jTextField1.getText());
        out.flush();
        unhideElement();
        try {
            getData(jTextField1.getText());
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           
       
        if(jTextField1.getText().length() == 3){
            //JMenu1
            unhideElement();
            
            if( ownResult.size() < 1){
                getDialog(this,"Sonuç Bulunamadı");
            }else if(ownResult.size() < 2){
                label2.setVisible(false);
                jLabel2.setVisible(false);
                label3.setVisible(false);
                jLabel3.setVisible(false);
                label4.setVisible(false);
                jLabel4.setVisible(false);
                label5.setVisible(false);
                jLabel5.setVisible(false);
                jLabel7.setVisible(false);
            }else if(ownResult.size() < 3){
                label3.setVisible(false);
                jLabel3.setVisible(false);
                label4.setVisible(false);
                jLabel4.setVisible(false);
                label5.setVisible(false);
                jLabel5.setVisible(false);
            }else if(ownResult.size() < 4){
                label4.setVisible(false);
                jLabel4.setVisible(false);
                label5.setVisible(false);
                jLabel5.setVisible(false);
            }else if(ownResult.size() < 5){
                label5.setVisible(false);
                jLabel5.setVisible(false);
            }
            
            for(int i = 0 ; i <  ownResult.size(); i++){
                label1.setText(ownResult.get(0).getTitle());
                jLabel1.setText(ownResult.get(0).getUrl());
            
                label2.setText(ownResult.get(1).getTitle());
                jLabel2.setText(ownResult.get(1).getUrl());
            
                label3.setText(ownResult.get(2).getTitle());
                jLabel3.setText(ownResult.get(2).getUrl());
            
                label4.setText(ownResult.get(3).getTitle());
                jLabel4.setText(ownResult.get(3).getUrl());
            
                label5.setText(ownResult.get(4).getTitle());
                jLabel5.setText(ownResult.get(4).getUrl());
             
            }
            
            BufferedImage img=null;
            ArrayList<File> ff=new ArrayList<File>();
            listf("/home/canerbakar/Desktop/filesendtestfolder1",ff);
            
            for (int z = 0; z < 5; z++) {
                        
                try {
                    img = ImageIO.read(new File(
                    ff.get(z).getAbsolutePath()));
                } catch (IOException ex) {

                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                ImageIcon icon=new ImageIcon(img);
                if ( z % 5 ==  0 )
                    jLabel7.setIcon(icon);
                else if ( z % 5 == 1)
                    jLabel8.setIcon(icon);
                else if ( z % 5 == 2)
                    jLabel9.setIcon(icon);
                else if ( z % 5 == 3)
                    jLabel10.setIcon(icon);
                else if ( z % 5 == 4)
                    jLabel11.setIcon(icon);

            }
            
            JMenuItem addingItem = new JMenuItem(jTextField1.getText());
            jMenu1.add(addingItem);
            try {
                toEncode(jTextField1.getText());
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            
            }else{
                getDialog(this,"Aramayı lütfen 3 harfli kelimeler ile yapın.");
            }
    }//GEN-LAST:event_jButton1MousePressed

   
     
    public String toEncode(String str) throws IOException{
        
        File fileDir = new File("/home/canerbakar/Desktop/historyLog.txt");
        try {
            fw = new FileWriter(fileDir.getAbsoluteFile(),true);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String encoded = DatatypeConverter.printBase64Binary(str.getBytes());
        BufferedWriter bw = new BufferedWriter(fw);
        bw.write(encoded+'\n');
        
        bw.close();
        return encoded;
    }
    
    public String toDecode(String str){
        String decoded = new String(DatatypeConverter.parseBase64Binary(str));
        return decoded;
    }
    
    
    public void getDialog(JFrame aFrame, String message){
        JOptionPane.showMessageDialog(aFrame, message);
    }
    
    private void label1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MousePressed
       java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel1.getText());
                x.setVisible(true);
                
          }
        });
    }//GEN-LAST:event_label1MousePressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
         
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        // Enter was pressed. Your code goes here.
        if(jTextField1.getText().length() <= 3){
            out.println(jTextField1.getText());
            out.flush();
            unhideElement();
            try{
                getData(jTextField1.getText());
            }catch(IOException myExp){
                System.out.println(myExp.toString());
            }
            
            int maxPageNumber = ownResult.indexOf(0);
            System.out.println(maxPageNumber);
            
        }else{
            getDialog(this,"Aramayı lütfen 3 harfli kelimeler ile yapın.");
        }
       
        if(jTextField1.getText().length() == 3){
            //JMenu1
            unhideElement();
            
            if( ownResult.size() < 1){
                getDialog(this,"Sonuç Bulunamadı");
            }else if(ownResult.size() < 2){
                label2.setVisible(false);
                jLabel2.setVisible(false);
                label3.setVisible(false);
                jLabel3.setVisible(false);
                label4.setVisible(false);
                jLabel4.setVisible(false);
                label5.setVisible(false);
                jLabel5.setVisible(false);
                jLabel7.setVisible(false);
            }else if(ownResult.size() < 3){
                label3.setVisible(false);
                jLabel3.setVisible(false);
                label4.setVisible(false);
                jLabel4.setVisible(false);
                label5.setVisible(false);
                jLabel5.setVisible(false);
            }else if(ownResult.size() < 4){
                label4.setVisible(false);
                jLabel4.setVisible(false);
                label5.setVisible(false);
                jLabel5.setVisible(false);
            }else if(ownResult.size() < 5){
                label5.setVisible(false);
                jLabel5.setVisible(false);
            }
            
            for(int i = 0 ; i <  ownResult.size(); i++){
                label1.setText(ownResult.get(0).getTitle());
                jLabel1.setText(ownResult.get(0).getUrl());
            
                label2.setText(ownResult.get(1).getTitle());
                jLabel2.setText(ownResult.get(1).getUrl());
            
                label3.setText(ownResult.get(2).getTitle());
                jLabel3.setText(ownResult.get(2).getUrl());
            
                label4.setText(ownResult.get(3).getTitle());
                jLabel4.setText(ownResult.get(3).getUrl());
            
                label5.setText(ownResult.get(4).getTitle());
                jLabel5.setText(ownResult.get(4).getUrl());
                
                BufferedImage img=null;
                ArrayList<File> ff=new ArrayList<File>();
                
            }
            
            BufferedImage img=null;
            ArrayList<File> ff=new ArrayList<File>();
            listf("/home/canerbakar/Desktop/filesendtestfolder1",ff);
            
            for (int z = 0; z < 5; z++) {

                try {

                    img = ImageIO.read(new File(
                    ff.get(z).getAbsolutePath()));
                } catch (IOException ex) {

                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                ImageIcon icon=new ImageIcon(img);
                if ( z % 5 ==  0 ){
                    jLabel7.setIcon(icon);
                    //jLabel7.setText(jLabel1.getText());
                }
                else if ( z % 5 == 1){
                    jLabel8.setIcon(icon);
                    /*jLabel8.setText(jLabel2.getText());*/
                }
                else if ( z % 5 == 2){
                    jLabel9.setIcon(icon);
                   // jLabel7.setText(jLabel3.getText());
                }
                else if ( z % 5 == 3){
                    jLabel10.setIcon(icon);
                    //jLabel10.setText(jLabel4.getText());
                }
                else if ( z % 5 == 4){
                    jLabel11.setIcon(icon);
                    //jLabel10.setText(jLabel5.getText());
                }

            }
            
            
            JMenuItem addingItem = new JMenuItem(jTextField1.getText());
            jMenu1.add(addingItem);
            try {
                toEncode(jTextField1.getText());
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    public void listf(String directoryName, ArrayList<File> files) {
        File directory = new File(directoryName);

    
        File[] fList = directory.listFiles();
        for (File file : fList) {
            if (file.isFile()) {
                files.add(file);
            } else if (file.isDirectory()) {
                listf(file.getAbsolutePath(), files);
            }
        }
    }
    
    
    private void label2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MousePressed
        System.out.println("Label2 tıklandı");
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel2.getText());
                x.setVisible(true);
                
          }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_label2MousePressed

    private void label3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MousePressed
        System.out.println("Label3 tıklandı");
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel3.getText());
                x.setVisible(true);
                
          }
    });
        // TODO add your handling code here:
    }//GEN-LAST:event_label3MousePressed

    private void label4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MousePressed
        // TODO add your handling code here:,
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel4.getText());
                x.setVisible(true);
                
          }
    });
        System.out.println("Label4 tıklandı");
    }//GEN-LAST:event_label4MousePressed

    private void label5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MousePressed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel5.getText());
                x.setVisible(true);
                
          }
    });
        System.out.println("Label5 tıklandı");
    }//GEN-LAST:event_label5MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
              System.out.println(jLabel1.getText());
                WebFrame x = new WebFrame(jLabel1.getText());
                x.setVisible(true);
                
          }
    });
        System.out.println("Label1 DEsc tıklandı");
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel2.getText());
                x.setVisible(true);
                
          }
    });
        System.out.println("Label2 Desc tıklandı");
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel3.getText());
                x.setVisible(true);
                
          }
    });
        System.out.println("Label3 Desc tıklandı");
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel4.getText());
                x.setVisible(true);
                
          }
    });
        System.out.println("Label4 Desc tıklandı");
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel5.getText());
                x.setVisible(true);
                
          }
    });
        System.out.println("Label5 Desc tıklandı");
    }//GEN-LAST:event_jLabel5MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //resetElementHide();
        
        System.out.println("Page < tıklandı");
        System.out.println("OwnResult size = " + ownResult.size() );
        
        int maxIndex=20;
        if(ownResult.size() % 5 != 0){
            maxIndex += 1;
        }
        System.out.println("MAX INDEX = " + maxIndex);
        
        if(pageIndex + 1 > maxIndex){
            getDialog(this," Maximum sayfa sayısı aşılamaz !");
        }else
        {
            pageIndex += 1;
            out.println(pageIndex);
            out.flush();
            if(pageIndex == maxIndex){
                try {
                    checkLastPage();
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                try {
                    getData1();
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                checkinterPages(pageIndex);
            }
            
            jLabel6.setText("Page "+pageIndex);
        }

        System.out.println("Şuan "+ pageIndex + ". sayfadasınız");
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int maxIndex = ownResult.size() / 5;
        if(ownResult.size() % 5 != 0){
            maxIndex += 1;
        }
        System.out.println("Page > tıklandı");
        System.out.println("OwnResult size = " + ownResult.size() );
        if(pageIndex - 1 < 1){
            getDialog(this," 0. sayfaya erişmeye çalıştınız");
        }else{
            pageIndex -= 1;
            if(pageIndex > 1){
                try {
                    getData1();
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
               checkinterPages(pageIndex);
            }
            if(pageIndex == 1){
               checkFirstPage();
            }
            jLabel6.setText("Page "+pageIndex);
        }
        System.out.println("Şuan "+ pageIndex + ". sayfadasınız");
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /*
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked
    */
    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
       java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel1.getText());
                x.setVisible(true);
                
          }
    });
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
       java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel2.getText());
                x.setVisible(true);
                
          }
    });
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel3.getText());
                x.setVisible(true);
                
          }
    });
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel4.getText());
                x.setVisible(true);
                
          }
    });
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                WebFrame x = new WebFrame(jLabel5.getText());
                x.setVisible(true);
                
          }
    });
    }//GEN-LAST:event_jLabel11MousePressed
   
   
    
    
    
    public void checkinterPages(int pageInt){
        label1.setVisible(true);
        System.out.println("asdasdasda:" + ownResult.size());
        label1.setText(ownResult.get(0).getUrl());
        label2.setVisible(true);
        label2.setText(ownResult.get(1).getUrl());
        label3.setVisible(true);
        label3.setText(ownResult.get(2).getUrl());
        label4.setVisible(true);
        label4.setText(ownResult.get(3).getUrl());
        label5.setVisible(true);
        label5.setText(ownResult.get(4).getUrl());
        jLabel1.setVisible(true);
        jLabel1.setText(ownResult.get(0).getTitle());
        jLabel2.setVisible(true);
        jLabel2.setText(ownResult.get(1).getTitle());
        jLabel3.setVisible(true);
        jLabel3.setText(ownResult.get(2).getTitle());
        jLabel4.setVisible(true);
        jLabel4.setText(ownResult.get(3).getTitle());
        jLabel5.setVisible(true);
        jLabel5.setText(ownResult.get(4).getTitle());
    }
    
    public void checkFirstPage(){
        if(ownResult.size() >= 5){
            label1.setVisible(true);
            label1.setText(ownResult.get(0).getUrl());
            label2.setVisible(true);
            label2.setText(ownResult.get(1).getUrl());
            label3.setVisible(true);
            label3.setText(ownResult.get(2).getUrl());
            label4.setVisible(true);
            label4.setText(ownResult.get(3).getUrl());
            label5.setVisible(true);
            label5.setText(ownResult.get(4).getUrl());
            jLabel1.setVisible(true);
            jLabel1.setText(ownResult.get(0).getTitle());
            jLabel2.setVisible(true);
            jLabel2.setText(ownResult.get(1).getTitle());
            jLabel3.setVisible(true);
            jLabel3.setText(ownResult.get(2).getTitle());
            jLabel4.setVisible(true);
            jLabel4.setText(ownResult.get(3).getTitle());
            jLabel5.setVisible(true);
            jLabel5.setText(ownResult.get(4).getTitle());
        }else if(ownResult.size() % 5 == 1){
            label1.setText(ownResult.get(0).getUrl());
            label2.setVisible(false);
            label3.setVisible(false);
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel1.setText(ownResult.get(0).getTitle());
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
        }else if(ownResult.size() % 5 == 2){
            label1.setText(ownResult.get(0).getUrl());
            jLabel1.setText(ownResult.get(0).getTitle());
            label2.setText(ownResult.get(1).getUrl());
            jLabel2.setText(ownResult.get(1).getTitle());
            
            label3.setVisible(false);
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
        }else if(ownResult.size() % 5 == 3){
            label1.setText(ownResult.get(0).getUrl());
            jLabel1.setText(ownResult.get(0).getTitle());
            label2.setText(ownResult.get(1).getUrl());
            jLabel2.setText(ownResult.get(1).getTitle());
            label3.setText(ownResult.get(2).getUrl());
            jLabel3.setText(ownResult.get(2).getTitle());
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
        }else if(ownResult.size() % 5 == 4){
            label1.setText(ownResult.get(0).getUrl());
            jLabel1.setText(ownResult.get(0).getTitle());
            label2.setText(ownResult.get(1).getUrl());
            jLabel2.setText(ownResult.get(1).getTitle());
            label3.setText(ownResult.get(2).getUrl());
            jLabel3.setText(ownResult.get(2).getTitle());
            label4.setText(ownResult.get(3).getUrl());
            jLabel4.setText(ownResult.get(3).getTitle());
            label4.setVisible(false);
            jLabel4.setVisible(false);
        }else
        {
            System.out.println("Else case");
        }
    }
    
    public void checkLastPage() throws IOException{
        
        if(ownResult.size() % 5 == 0){
            label1.setVisible(true);
            label2.setVisible(true);
            label3.setVisible(true);
            label4.setVisible(true);
            label5.setVisible(true);
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel7.setVisible(true);
            label1.setText(ownResult.get(ownResult.size()-5).getUrl());
            jLabel1.setText(ownResult.get(ownResult.size()-5).getTitle());
            label2.setText(ownResult.get(ownResult.size()-4).getUrl());
            jLabel2.setText(ownResult.get(ownResult.size()-4).getTitle());
            label3.setText(ownResult.get(ownResult.size()-3).getUrl());
            jLabel3.setText(ownResult.get(ownResult.size()-3).getTitle());
            label4.setText(ownResult.get(ownResult.size()-2).getUrl());
            jLabel4.setText(ownResult.get(ownResult.size()-2).getTitle());
            label5.setText(ownResult.get(ownResult.size()-1).getUrl());
            jLabel5.setText(ownResult.get(ownResult.size()-1).getTitle());
            
            
            
            
            
        }else if(ownResult.size() % 5 == 1){
            label2.setVisible(false);
            label3.setVisible(false);
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            
            label1.setText(ownResult.get(ownResult.size()-5).getUrl());
            jLabel1.setText(ownResult.get(ownResult.size()-5).getTitle());
            label2.setText(ownResult.get(ownResult.size()-4).getUrl());
            jLabel2.setText(ownResult.get(ownResult.size()-4).getTitle());
            label3.setText(ownResult.get(ownResult.size()-3).getUrl());
            jLabel3.setText(ownResult.get(ownResult.size()-3).getTitle());
            label4.setText(ownResult.get(ownResult.size()-2).getUrl());
            jLabel4.setText(ownResult.get(ownResult.size()-2).getTitle());
            label5.setText(ownResult.get(ownResult.size()-1).getUrl());
            jLabel5.setText(ownResult.get(ownResult.size()-1).getTitle());
            
        }else if(ownResult.size() % 5 == 2){
            label3.setVisible(false);
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            
            label1.setText(ownResult.get(ownResult.size()-5).getUrl());
            jLabel1.setText(ownResult.get(ownResult.size()-5).getTitle());
            label2.setText(ownResult.get(ownResult.size()-4).getUrl());
            jLabel2.setText(ownResult.get(ownResult.size()-4).getTitle());
            label3.setText(ownResult.get(ownResult.size()-3).getUrl());
            jLabel3.setText(ownResult.get(ownResult.size()-3).getTitle());
            label4.setText(ownResult.get(ownResult.size()-2).getUrl());
            jLabel4.setText(ownResult.get(ownResult.size()-2).getTitle());
            label5.setText(ownResult.get(ownResult.size()-1).getUrl());
            jLabel5.setText(ownResult.get(ownResult.size()-1).getTitle());
        }else if(ownResult.size() % 5 == 3){
            label4.setVisible(false);
            label5.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            label1.setText(ownResult.get(ownResult.size()-5).getUrl());
            jLabel1.setText(ownResult.get(ownResult.size()-5).getTitle());
            label2.setText(ownResult.get(ownResult.size()-4).getUrl());
            jLabel2.setText(ownResult.get(ownResult.size()-4).getTitle());
            label3.setText(ownResult.get(ownResult.size()-3).getUrl());
            jLabel3.setText(ownResult.get(ownResult.size()-3).getTitle());
            label4.setText(ownResult.get(ownResult.size()-2).getUrl());
            jLabel4.setText(ownResult.get(ownResult.size()-2).getTitle());
            label5.setText(ownResult.get(ownResult.size()-1).getUrl());
            jLabel5.setText(ownResult.get(ownResult.size()-1).getTitle());
            
        }else if(ownResult.size() % 5 == 4){
            label4.setVisible(false);
            jLabel4.setVisible(false);
            
            label1.setText(ownResult.get(ownResult.size()-5).getUrl());
            jLabel1.setText(ownResult.get(ownResult.size()-5).getTitle());
            label2.setText(ownResult.get(ownResult.size()-4).getUrl());
            jLabel2.setText(ownResult.get(ownResult.size()-4).getTitle());
            label3.setText(ownResult.get(ownResult.size()-3).getUrl());
            jLabel3.setText(ownResult.get(ownResult.size()-3).getTitle());
            label4.setText(ownResult.get(ownResult.size()-2).getUrl());
            jLabel4.setText(ownResult.get(ownResult.size()-2).getTitle());
            label5.setText(ownResult.get(ownResult.size()-1).getUrl());
            jLabel5.setText(ownResult.get(ownResult.size()-1).getTitle());
        }
    }
  


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        
    
        String ip ="127.0.0.1";
        sendRequest(ip);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    NewJFrame neww= new NewJFrame();
                    neww.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
   /* Elementleri saklar */
    public void hideElement(){
         jLabel1.setVisible(false);
         jLabel2.setVisible(false);
         jLabel3.setVisible(false);
         jLabel4.setVisible(false);
         jLabel5.setVisible(false);
         label1.setVisible(false);
         label2.setVisible(false);
         label3.setVisible(false);
         label4.setVisible(false);
         label5.setVisible(false);
         jButton3.setVisible(false);
         jButton2.setVisible(false);
         jLabel6.setVisible(false);
         jLabel7.setVisible(false);
         jLabel8.setVisible(false);
         jLabel9.setVisible(false);
         jLabel10.setVisible(false);
         jLabel11.setVisible(false);
    }
    
    /* Elementleri gösterir */
    public void unhideElement(){
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        label1.setVisible(true);
        label2.setVisible(true);
        label3.setVisible(true);
        label4.setVisible(true);
        label5.setVisible(true);
        jButton3.setVisible(true);
        jButton2.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables


    

    public void setSite(String []site){
        result1=site;
    }

    public String []getSite(){
        return result1;
    }
    
}




  
    
    


